version: '3'

# Configuration is in resources/application.yml
vars: {}

tasks:
  # ==============================
  # MAIN TASKS - FOR DIRECT USAGE
  # ==============================
  
  generate:
    desc: Generate clients from pinned submodule commit
    summary: |
      Generates Go clients from OpenAPI specs using the pinned submodule commit.
      This ensures deterministic builds. To update the submodule first, use 'task update-submodule'.
    cmds:
      - task: init
      - task: generate-code

  update-submodule:
    desc: Update submodule to latest commit (explicit action)
    summary: |
      Updates the SDK submodule to the latest commit on main branch.
      After running this, review the changes and commit if desired to pin the new version.

      Usage:
        task update-submodule
        git status  # Review submodule changes
        git add external/sdk
        git commit -m "chore: Update SDK submodule to latest"
    cmds:
      - echo "Updating SDK submodule to latest commit on main..."
      - cd external/sdk && git checkout main && git pull origin main && cd ../..
      - echo "✓ Submodule updated. Review changes with 'git status' and commit if desired."

  # ==============================
  # UTILITY TASKS - INTERNAL USE
  # ==============================
  
  init:
    internal: true
    desc: Initialize git submodules using pinned commit
    cmds:
      # Initialize and update submodules to the commit referenced in the parent repo
      # This ensures deterministic builds by using the pinned commit
      - git submodule update --init --recursive
      - echo "✓ Submodules initialized to pinned commits"
    status:
      - test -f external/sdk/sdk-packages/aml-sdk/openapi.json

  generate-code:
    internal: true
    desc: Generate Go clients from OpenAPI specs
    deps: [init]
    cmds:
      - |
        # Process OpenAPI specs and generate clients
        # Configuration is in resources/application.yml
        # To override defaults, set environment variables:
        # - SPECS_DIR: Directory containing OpenAPI specs
        # - OUTPUT_DIR: Output directory for generated clients
        # - TARGET_SERVICES: Regex pattern to filter services
        go run main.go
      - go mod tidy
    # The 'sources' field defines input files that this task depends on.
    # Taskfile tracks these files and only runs the task if any of them have changed.
    # This provides efficient incremental builds - the task only runs when necessary.
    sources:
      - ./external/sdk/sdk-packages/*/openapi.json  # OpenAPI spec files
      - ogen.yml                                    # Ogen configuration
      - main.go                                     # Main generation code
      - internal/**/*.go                            # Internal generation code
      - resources/application.yml                   # Configuration file
    # The 'generates' field defines output files/directories that this task creates.
    # Taskfile compares timestamps between source and generated files.
    # The task runs only if source files are newer than generated files or if generated files don't exist.
    # This prevents unnecessary regeneration when nothing has changed.
    generates:
      - ./generated/                                # Main generated directory with all output files
